# Generated by Django 4.0.3 on 2022-04-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_article_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoringaMerch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Editor',
        ),
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default='no-image', upload_to='articles/'),
        ),
        migrations.AlterField(
            model_name='newsletterrecipients',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
